### ISSUE TITLE
Unit test not working

### ISSUE THREAD

**Issue by khanharis87** [ryutamaki/vue-template-webpack-typescript#7]
Desperatley looking for an enviroment where I can run test with typescript, mocha, chai. Current template give me following errors. You think including babel-loader for .js files will be a good idea?
I get a lot of warnings, but here are the errors:
cmd : yarn run unit

`PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///test/unit/index.js:8:0 <- index.js:19292`

&&

`ERROR [karma]: { Error: EACCES: permission denied, mkdir '/Users/haris/Documents/typscr-vue/test/unit/coverage'`

**Comment by ryutamaki** [comment]
you are right and this is duplicated issue.
please use this https://github.com/ryutamaki/vue-template-webpack-typescript/issues/5
